// pages/kontakt.vue
<template>
  <div class="min-h-screen">
    <!-- Header -->
    <div class="bg-gray-50 py-12">
      <div class="container mx-auto px-4">
        <h1 class="text-4xl font-bold text-center mb-4">{{ page?.title }}</h1>
        <p class="text-xl text-gray-600 text-center max-w-3xl mx-auto">{{ page?.description }}</p>
      </div>
    </div>

    <div class="container mx-auto px-4 py-12">
      <div class="grid lg:grid-cols-2 gap-12">
        <!-- Contact Information -->
        <div>
          <h2 class="text-2xl font-bold mb-6">Kontakt information</h2>
          
          <div class="space-y-6">
            <!-- Phone -->
            <div v-if="page?.contactInfo?.phone" class="flex items-start space-x-4">
              <div class="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <Icon name="heroicons:phone" class="w-6 h-6 text-primary-600" />
              </div>
              <div>
                <h3 class="font-semibold text-lg">Telefon</h3>
                <a :href="`tel:${page.contactInfo.phone}`" class="text-primary-600 hover:text-primary-700 text-lg">
                  {{ page.contactInfo.phone }}
                </a>
                <p class="text-gray-600 text-sm">{{ page.contactInfo.phoneHours }}</p>
              </div>
            </div>

            <!-- Email -->
            <div v-if="page?.contactInfo?.email" class="flex items-start space-x-4">
              <div class="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <Icon name="heroicons:envelope" class="w-6 h-6 text-primary-600" />
              </div>
              <div>
                <h3 class="font-semibold text-lg">Email</h3>
                <a :href="`mailto:${page.contactInfo.email}`" class="text-primary-600 hover:text-primary-700 text-lg">
                  {{ page.contactInfo.email }}
                </a>
                <p class="text-gray-600 text-sm">{{ page.contactInfo.emailResponse }}</p>
              </div>
            </div>

            <!-- Address -->
            <div v-if="page?.contactInfo?.address" class="flex items-start space-x-4">
              <div class="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <Icon name="heroicons:map-pin" class="w-6 h-6 text-primary-600" />
              </div>
              <div>
                <h3 class="font-semibold text-lg">Adresse</h3>
                <p class="text-gray-700">{{ page.contactInfo.address }}</p>
              </div>
            </div>

            <!-- Emergency -->
            <div v-if="page?.contactInfo?.emergencyPhone" class="flex items-start space-x-4">
              <div class="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <Icon name="heroicons:exclamation-triangle" class="w-6 h-6 text-red-600" />
              </div>
              <div>
                <h3 class="font-semibold text-lg">Akut service</h3>
                <a :href="`tel:${page.contactInfo.emergencyPhone}`" class="text-red-600 hover:text-red-700 text-lg">
                  {{ page.contactInfo.emergencyPhone }}
                </a>
                <p class="text-gray-600 text-sm">{{ page.contactInfo.emergencyHours }}</p>
              </div>
            </div>
          </div>

          <!-- Service Areas -->
          <div v-if="page?.serviceAreas" class="mt-12">
            <h2 class="text-2xl font-bold mb-6">{{ page.serviceAreas.title }}</h2>
            <p class="text-gray-600 mb-6">{{ page.serviceAreas.description }}</p>
            <div class="grid grid-cols-2 gap-4">
              <div v-for="area in page.serviceAreas.areas" :key="area" class="flex items-center space-x-2">
                <Icon name="heroicons:check-circle" class="w-5 h-5 text-green-500" />
                <span>{{ area }}</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Contact Form -->
        <div class="bg-gray-50 p-8 rounded-lg">
          <h2 class="text-2xl font-bold mb-6">{{ page?.contactForm?.title || 'Send os en besked' }}</h2>
          
          <form @submit.prevent="submitForm" class="space-y-6">
            <div class="grid md:grid-cols-2 gap-6">
              <div>
                <label for="name" class="block text-sm font-medium text-gray-700 mb-2">Navn *</label>
                <input
                  id="name"
                  v-model="form.name"
                  type="text"
                  required
                  class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                />
              </div>
              
              <div>
                <label for="phone" class="block text-sm font-medium text-gray-700 mb-2">Telefon *</label>
                <input
                  id="phone"
                  v-model="form.phone"
                  type="tel"
                  required
                  class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                />
              </div>
            </div>

            <div>
              <label for="email" class="block text-sm font-medium text-gray-700 mb-2">Email *</label>
              <input
                id="email"
                v-model="form.email"
                type="email"
                required
                class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
            </div>

            <div v-if="page?.contactForm?.serviceOptions">
              <label for="service" class="block text-sm font-medium text-gray-700 mb-2">Type ydelse</label>
              <select
                id="service"
                v-model="form.service"
                class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              >
                <option value="">Vælg ydelse</option>
                <option v-for="option in page.contactForm.serviceOptions" :key="option.value" :value="option.value">
                  {{ option.label }}
                </option>
              </select>
            </div>

            <div>
              <label for="message" class="block text-sm font-medium text-gray-700 mb-2">Besked *</label>
              <textarea
                id="message"
                v-model="form.message"
                rows="5"
                required
                class="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                placeholder="Fortæl os om dit projekt..."
              ></textarea>
            </div>

            <div>
              <button
                type="submit"
                :disabled="isSubmitting"
                class="w-full bg-primary-500 text-white py-3 px-6 rounded-lg hover:bg-primary-600 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
              >
                {{ isSubmitting ? 'Sender...' : (page?.contactForm?.submitButtonText || 'Send besked') }}
              </button>
            </div>

            <p v-if="page?.contactForm?.privacyNotice" class="text-sm text-gray-600">
              {{ page.contactForm.privacyNotice }}
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const { page } = useContent()

const form = ref({
  name: '',
  phone: '',
  email: '',
  service: '',
  message: ''
})

const isSubmitting = ref(false)

const submitForm = async () => {
  isSubmitting.value = true
  
  // Simulate form submission
  await new Promise(resolve => setTimeout(resolve, 1000))
  
  // In a real app, you'd send this to your backend
  console.log('Form submitted:', form.value)
  
  // Reset form
  form.value = {
    name: '',
    phone: '',
    email: '',
    service: '',
    message: ''
  }
  
  isSubmitting.value = false
  
  // Show success message (you could use a toast library)
  alert('Tak for din besked! Vi vender tilbage hurtigst muligt.')
}
</script>

// app/kontakt/page.tsx
import { contactPageData } from '@/app/data/staticContent';

export default function KontaktPage() {
  const data = contactPageData;

  return (
    <main className="py-20">
      <div className="container">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold text-gray-800 mb-6">
              {data.title}
            </h1>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              {data.description}
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-12">
            {/* Contact Information */}
            <div className="space-y-8">
              <div>
                <h2 className="text-2xl font-bold text-gray-800 mb-6">
                  Kontaktoplysninger
                </h2>
                
                <div className="space-y-6">
                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center flex-shrink-0">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="font-semibold text-gray-800 mb-1">Telefon</h3>
                      <p className="text-gray-600">{data.contactInfo.phone}</p>
                      <p className="text-sm text-gray-500">{data.contactInfo.phoneHours}</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center flex-shrink-0">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="font-semibold text-gray-800 mb-1">Email</h3>
                      <p className="text-gray-600">{data.contactInfo.email}</p>
                      <p className="text-sm text-gray-500">{data.contactInfo.emailResponse}</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center flex-shrink-0">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="font-semibold text-gray-800 mb-1">Adresse</h3>
                      <div className="text-gray-600 whitespace-pre-line">
                        {data.contactInfo.address}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-start gap-4">
                    <div className="w-12 h-12 bg-blue-600 rounded-lg flex items-center justify-center flex-shrink-0">
                      <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="font-semibold text-gray-800 mb-1">Akut Service</h3>
                      <p className="text-gray-600">{data.contactInfo.emergencyPhone}</p>
                      <p className="text-sm text-gray-500">{data.contactInfo.emergencyHours}</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Service Areas */}
              <div>
                <h3 className="text-xl font-semibold text-gray-800 mb-4">
                  {data.serviceAreas.title}
                </h3>
                <p className="text-gray-600 mb-4">
                  {data.serviceAreas.description}
                </p>
                <ul className="text-gray-600 space-y-2">
                  {data.serviceAreas.areas.map((area, index) => (
                    <li key={index}>• {area}</li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Contact Form */}
            <div>
              <div className="bg-gray-50 p-8 rounded-lg">
                <h2 className="text-2xl font-bold text-gray-800 mb-6">
                  {data.contactForm.title}
                </h2>
                
                <form className="space-y-6">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <label htmlFor="fornavn" className="block text-sm font-medium text-gray-700 mb-2">
                        Fornavn *
                      </label>
                      <input
                        type="text"
                        id="fornavn"
                        name="fornavn"
                        required
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                    <div>
                      <label htmlFor="efternavn" className="block text-sm font-medium text-gray-700 mb-2">
                        Efternavn *
                      </label>
                      <input
                        type="text"
                        id="efternavn"
                        name="efternavn"
                        required
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      />
                    </div>
                  </div>

                  <div>
                    <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
                      Email *
                    </label>
                    <input
                      type="email"
                      id="email"
                      name="email"
                      required
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>

                  <div>
                    <label htmlFor="telefon" className="block text-sm font-medium text-gray-700 mb-2">
                      Telefon
                    </label>
                    <input
                      type="tel"
                      id="telefon"
                      name="telefon"
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>

                  <div>
                    <label htmlFor="service" className="block text-sm font-medium text-gray-700 mb-2">
                      Type service
                    </label>
                    <select
                      id="service"
                      name="service"
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    >
                      {data.contactForm.serviceOptions.map((option, index) => (
                        <option key={index} value={option.value}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label htmlFor="besked" className="block text-sm font-medium text-gray-700 mb-2">
                      Besked *
                    </label>
                    <textarea
                      id="besked"
                      name="besked"
                      rows={5}
                      required
                      placeholder="Beskriv dit projekt eller dine behov..."
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    ></textarea>
                  </div>

                  <button
                    type="submit"
                    className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-lg transition-colors"
                  >
                    {data.contactForm.submitButtonText}
                  </button>

                  <p className="text-sm text-gray-500 text-center">
                    {data.contactForm.privacyNotice}
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
