// app/galleri/page.tsx
import Link from "next/link";
import Image from "next/image";
import { IconComponent } from "@/app/components/IconComponent";
import { galleryPageData } from "@/app/data/staticContent";

// Gallery image component
function GalleryImage({ 
  image, 
  onImageClick 
}: { 
  image: typeof galleryPageData.images[0]; 
  onImageClick?: () => void; 
}) {
  return (
    <div className="group cursor-pointer" onClick={onImageClick}>
      <div className="relative aspect-square bg-gray-200 rounded-lg overflow-hidden">
        <Image
          src={image.image.asset.url}
          alt={image.image.alt}
          fill
          className="object-cover"
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
        
        {/* Hover overlay */}
        <div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-70 transition-all duration-300 flex items-center justify-center">
          <div className="text-white text-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <IconComponent name="search" className="w-12 h-12 mx-auto mb-2" />
            <p className="text-sm font-medium">Se større billede</p>
          </div>
        </div>
      </div>
      
      <div className="mt-4">
        <h3 className="font-semibold text-gray-800">{image.title}</h3>
        <p className="text-sm text-gray-600 mt-1">{image.description}</p>
      </div>
    </div>
  );
}

// Main gallery page component
export default function GalleriPage() {
  const data = galleryPageData;

  return (
    <main className="py-20">
      <div className="container">
        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-800 mb-6">
            {data.title}
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            {data.description}
          </p>
        </div>

        {/* Filter Tabs */}
        <div className="flex flex-wrap justify-center gap-4 mb-12">
          {data.categories.map((category, index) => (
            <button 
              key={category.slug}
              className={`px-6 py-2 rounded-full font-medium transition-colors ${
                index === 0 
                  ? 'bg-blue-600 text-white hover:bg-blue-700' 
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              {category.name}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {data.images.map((image, index) => (
            <GalleryImage key={index} image={image} />
          ))}
        </div>

        {/* Load More Button */}
        <div className="text-center mt-12">
          <button className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-lg font-semibold transition-colors">
            {data.loadMoreText}
          </button>
        </div>

        {/* Call to Action */}
        <div className="bg-gray-50 rounded-lg p-8 mt-16 text-center">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">
            {data.callToAction.title}
          </h2>
          <p className="text-gray-600 mb-6 max-w-2xl mx-auto">
            {data.callToAction.description}
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/kontakt"
              className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-lg font-semibold transition-colors"
            >
              {data.callToAction.primaryButtonText}
            </Link>
            <a
              href={`tel:${data.callToAction.phoneNumber}`}
              className="border-2 border-blue-600 text-blue-600 hover:bg-blue-600 hover:text-white px-8 py-3 rounded-lg font-semibold transition-colors"
            >
              {data.callToAction.secondaryButtonText}
            </a>
          </div>
        </div>
      </div>
    </main>
  );
}

// nuxt/pages/galleri.vue
<template>
  <div class="min-h-screen">
    <!-- Header -->
    <div class="bg-gray-50 py-12">
      <div class="container mx-auto px-4">
        <h1 class="text-4xl font-bold text-center mb-4">{{ page?.title }}</h1>
        <p class="text-xl text-gray-600 text-center max-w-3xl mx-auto">{{ page?.description }}</p>
      </div>
    </div>

    <!-- Category Filter -->
    <div v-if="page?.categories" class="sticky top-0 bg-white shadow-sm z-10 py-4">
      <div class="container mx-auto px-4">
        <div class="flex flex-wrap gap-2 justify-center">
          <button
            v-for="category in page.categories"
            :key="category.slug"
            @click="activeCategory = category.slug"
            :class="[
              'px-4 py-2 rounded-full font-medium transition-colors',
              activeCategory === category.slug
                ? 'bg-primary-500 text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            ]"
          >
            {{ category.name }}
          </button>
        </div>
      </div>
    </div>

    <!-- Gallery Grid -->
    <div class="container mx-auto px-4 py-8">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div
          v-for="image in filteredImages"
          :key="image.title"
          class="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-shadow cursor-pointer"
          @click="openLightbox(image)"
        >
          <NuxtImg
            :src="image.image"
            :alt="image.title"
            class="w-full h-64 object-cover group-hover:scale-105 transition-transform duration-300"
            loading="lazy"
          />
          <div class="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent opacity-0 group-hover:opacity-100 transition-opacity">
            <div class="absolute bottom-0 left-0 right-0 p-4 text-white">
              <h3 class="font-semibold text-lg">{{ image.title }}</h3>
              <p class="text-sm opacity-90">{{ image.description }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Load More -->
      <div v-if="hasMoreImages" class="text-center mt-8">
        <button
          @click="loadMore"
          class="px-6 py-3 bg-primary-500 text-white rounded-lg hover:bg-primary-600 transition-colors"
        >
          {{ page?.loadMoreText || 'Vis flere' }}
        </button>
      </div>
    </div>

    <!-- CTA Section -->
    <section v-if="page?.callToAction" class="py-16 bg-gray-50">
      <div class="container mx-auto px-4 text-center">
        <h2 class="text-3xl font-bold mb-4">{{ page.callToAction.title }}</h2>
        <p class="text-xl text-gray-600 mb-8">{{ page.callToAction.description }}</p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <NuxtLink to="/kontakt" class="px-6 py-3 bg-primary-500 text-white rounded-lg hover:bg-primary-600 transition-colors">
            {{ page.callToAction.primaryButtonText }}
          </NuxtLink>
          <a :href="`tel:${page.callToAction.phoneNumber}`" class="px-6 py-3 bg-white text-primary-500 border-2 border-primary-500 rounded-lg hover:bg-primary-50 transition-colors">
            {{ page.callToAction.secondaryButtonText }}
          </a>
        </div>
      </div>
    </section>

    <!-- Lightbox -->
    <div v-if="lightboxImage" @click="closeLightbox" class="fixed inset-0 bg-black/90 z-50 flex items-center justify-center p-4">
      <div class="relative max-w-4xl w-full">
        <button @click="closeLightbox" class="absolute -top-12 right-0 text-white hover:text-gray-300">
          <Icon name="heroicons:x-mark" class="w-8 h-8" />
        </button>
        <NuxtImg
          :src="lightboxImage.image"
          :alt="lightboxImage.title"
          class="w-full h-auto rounded-lg"
        />
        <div class="mt-4 text-white">
          <h3 class="text-xl font-semibold">{{ lightboxImage.title }}</h3>
          <p class="mt-2 text-gray-300">{{ lightboxImage.description }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
const { page } = useContent()

const activeCategory = ref('alle')
const displayCount = ref(6)
const lightboxImage = ref(null)

const filteredImages = computed(() => {
  if (!page.value?.images) return []
  
  const filtered = activeCategory.value === 'alle'
    ? page.value.images
    : page.value.images.filter(img => img.category === activeCategory.value)
  
  return filtered.slice(0, displayCount.value)
})

const hasMoreImages = computed(() => {
  if (!page.value?.images) return false
  const totalImages = activeCategory.value === 'alle'
    ? page.value.images.length
    : page.value.images.filter(img => img.category === activeCategory.value).length
  return displayCount.value < totalImages
})

const loadMore = () => {
  displayCount.value += 6
}

const openLightbox = (image) => {
  lightboxImage.value = image
}

const closeLightbox = () => {
  lightboxImage.value = null
}

// Reset display count when category changes
watch(activeCategory, () => {
  displayCount.value = 6
})
</script>
